services:
  canary:
   build: ./canary
   ports:
    - "5000:5000"
  gremlins:
    build: ./gremlins
    environment:
      -PYTHONUNBUFFERED: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  redis:
   image: redis:alpine


  postgres:
   image: postgres:15
   environment:
    POSTGRES_PASSWORD: secret

