services:
  canary:
   build: ./canary
   ports:
    - "5000:5000"
  gremlins:
    build: ./gremlins
    environment:
       PYTHONUNBUFFERED: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  medic:
    build: ./medic
    environment:
       PYTHONUNBUFFERED: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
   image: redis:alpine


  postgres:
   image: postgres:15
   environment:
    POSTGRES_PASSWORD: secret

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"

