global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'canary'
    static_configs:
      - targets: ['canary:5000']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
